# Generated by Django 4.0.4 on 2022-05-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments_author',
            field=models.CharField(max_length=150, verbose_name='Yorum'),
        ),
    ]
